version: "3"
services:
    proxy:
        image: nginx
        ports:
          - 80:80
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
          - app

    app:
        build: .
        expose:
          - 8009
        # depends_on:
        #   - db

    # db:
    #     image: mysql:5.7
    #     environment:
    #       MYSQL_DATABASE: test_db
    #       MYSQL_ROOT_PASSWORD: root
    #       MYSQL_ROOT_HOST: '%'
    #     ports:
    #       - 3306:3306